name: First Testing Github Action workflow YAML


on: 
    push: 
    workflow_dispatch: 

jobs: 
    testing: 
        name: Printing 
        runs-on: ubuntu-latest
        steps:
        - name: Using Action so they can read repo file
          uses: actions/checkout@v4
        - name: Printing Files
          run: echo ls
        - name: Listing Files
          run: |
              echo "Welcome To Github ACtions"